spring.application.name=bealquileres

server.port=8081

#### MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

##### Local
#spring.datasource.url = jdbc:mysql://alarcosj.esi.uclm.es:3306/tysweb2627alquileres?serverTimezone=Europe/Madrid&useSSL=false&&allowPublicKeyRetrieval=true

spring.datasource.url = jdbc:mysql://172.20.48.23:3306/tysweb2627alquileres?serverTimezone=Europe/Madrid&useSSL=false&&allowPublicKeyRetrieval=true
spring.datasource.username = tysweb2025
spring.datasource.password = tysweb2025

